### PR TITLE
fix(rosenpass): Fix duplicate key issue

### LINKED ISSUE #327: Duplicate exchanges in logs
Hi, I'm seeing duplicate log entries for exchanges, haven't yet verified if the file is actually changing multiple times.

```
output-key peer U0vVI3Uu/UnEGADyjdHgVjeab2cSQrE1AvkOpT+tWWA= key-file "key_out_21" exchanged
[2024-06-03T15:53:26Z WARN  rosenpass::app_server] No broker peer found for peer 21
output-key peer U0vVI3Uu/UnEGADyjdHgVjeab2cSQrE1AvkOpT+tWWA= key-file "key_out_21" exchanged
[2024-06-03T15:53:26Z WARN  rosenpass::app_server] No broker peer found for peer 21

```

Running latest HEAD as of today.

### PR DESCRIPTION
**Pull request by prabhpreet**
Change handle_init_conf to return to instruct key exchange on encountering new biscuit_no for peer

Fixes #327

### CODE REVIEW

**Comment by prabhpreet** [comment]
@aparcar Can you please test to see if it is fixed on your setup?

File: rosenpass/src/protocol.rs [hunk 1]
```diff
@@ -1947,7 +1948,12 @@ impl CryptoServer {
         Ok(peer)
     }
 
-    pub fn handle_init_conf(&mut self, ic: &InitConf, rc: &mut EmptyData) -> Result<PeerPtr> {
+    pub fn handle_init_conf(
+        &mut self,
+        ic: &InitConf,
+        rc: &mut EmptyData,
+    ) -> Result<(PeerPtr, bool)> {
+        let mut exchange = false;
```
Comment (koraa) [inline rosenpass/src/protocol.rs:1956]: `exchanged`

**Review by koraa — APPROVED** [review]
